/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { BuildingConfig, BuildingType } from './types';

// Map Settings
export const GRID_SIZE = 30;

// Game Settings
export const TICK_RATE_MS = 2000; // Game loop updates every 2 seconds
export const INITIAL_MONEY = 1000;

export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  [BuildingType.None]: {
    type: BuildingType.None,
    cost: 0,
    name: 'Hapus Aset',
    description: 'Menghapus properti dari tanah',
    color: '#ef4444', 
    popGen: 0,
    incomeGen: 0,
  },
  [BuildingType.Road]: {
    type: BuildingType.Road,
    cost: 20,
    name: 'Akses Jalan',
    description: 'Infrastruktur dasar bisnis.',
    color: '#475569', 
    popGen: 0,
    incomeGen: 0,
  },
  [BuildingType.Residential]: {
    type: BuildingType.Residential,
    cost: 150,
    name: 'Rumah Kontrakan',
    description: '+10 Kapasitas SDM',
    color: '#f87171', 
    popGen: 10,
    incomeGen: 0,
  },
  [BuildingType.Commercial]: {
    type: BuildingType.Commercial,
    cost: 300,
    name: 'Outlet Retail',
    description: '+$15 Profit Harian',
    color: '#60a5fa', 
    popGen: 0,
    incomeGen: 15,
  },
  [BuildingType.Industrial]: {
    type: BuildingType.Industrial,
    cost: 500,
    name: 'Pabrik Produksi',
    description: '+$40 Profit Harian',
    color: '#94a3b8', 
    popGen: 0,
    incomeGen: 40,
  },
  [BuildingType.Park]: {
    type: BuildingType.Park,
    cost: 100,
    name: 'Area Hijau',
    description: 'Meningkatkan nilai properti.',
    color: '#4ade80', 
    popGen: 1,
    incomeGen: 0,
  },
  [BuildingType.Mosque]: {
    type: BuildingType.Mosque,
    cost: 750,
    name: 'Fasilitas Umum',
    description: 'Meningkatkan kenyamanan.',
    color: '#10b981', 
    popGen: 5,
    incomeGen: 0,
  },
  [BuildingType.BigHouse]: {
    type: BuildingType.BigHouse,
    cost: 800,
    name: 'Villa Eksekutif',
    description: 'Hunian kelas bisnis. 2x1.',
    color: '#f87171',
    popGen: 25,
    incomeGen: 10,
    width: 2,
    depth: 1,
  },
  [BuildingType.Hospital]: {
    type: BuildingType.Hospital,
    cost: 2000,
    name: 'Klinik Utama',
    description: 'Layanan kesehatan premium. 2x2.',
    color: '#ffffff',
    popGen: 10,
    incomeGen: 20,
    width: 2,
    depth: 2,
  },
  [BuildingType.Skyscraper]: {
    type: BuildingType.Skyscraper,
    cost: 3500,
    name: 'Gedung Kantor',
    description: 'Headquarters utama. 1x1.',
    color: '#38bdf8',
    popGen: 50,
    incomeGen: 150,
  },
  [BuildingType.PowerPlant]: {
    type: BuildingType.PowerPlant,
    cost: 1500,
    name: 'Gardu Listrik',
    description: 'Sumber daya industri. 2x2.',
    color: '#94a3b8',
    popGen: 0,
    incomeGen: 200,
    width: 2,
    depth: 2,
  },
  [BuildingType.Kost]: {
    type: BuildingType.Kost,
    cost: 100,
    name: 'Kos Kerja',
    description: '+10 Kapasitas SDM.',
    color: '#fb923c',
    popGen: 10,
    incomeGen: 5,
  },
  [BuildingType.Laundry]: {
    type: BuildingType.Laundry,
    cost: 150,
    name: 'Laundry Kiloan',
    description: '+$20 Profit Harian.',
    color: '#38bdf8',
    popGen: 0,
    incomeGen: 20,
  },
  [BuildingType.Apotek]: {
    type: BuildingType.Apotek,
    cost: 200,
    name: 'Apotek Farmasi',
    description: '+$25 Profit Harian.',
    color: '#ffffff',
    popGen: 0,
    incomeGen: 25,
  },
  [BuildingType.Bengkel]: {
    type: BuildingType.Bengkel,
    cost: 250,
    name: 'Bengkel Servis',
    description: '+$35 Profit Harian.',
    color: '#475569',
    popGen: 0,
    incomeGen: 35,
  },
  [BuildingType.WarungMakan]: {
    type: BuildingType.WarungMakan,
    cost: 120,
    name: 'Rumah Makan',
    description: '+$18 Profit Harian.',
    color: '#facc15',
    popGen: 0,
    incomeGen: 18,
  },
  [BuildingType.Sekolah]: {
    type: BuildingType.Sekolah,
    cost: 1000,
    name: 'Sekolah Bisnis',
    description: 'Pusat pelatihan SDM. 1x1.',
    color: '#3b82f6',
    popGen: 20,
    incomeGen: 5,
  },
  [BuildingType.Universitas]: {
    type: BuildingType.Universitas,
    cost: 5000,
    name: 'Universitas',
    description: 'Akademi bisnis elit. 2x2.',
    color: '#6366f1',
    popGen: 100,
    incomeGen: 50,
    width: 2,
    depth: 2,
  },
};
